name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:  # ⬅️ SUBSTITUA APENAS ESTE JOB (da linha "test:" até o "deploy:")
    runs-on: ubuntu-latest
    
    steps:    # ⬅️ MANTENHA toda a estrutura acima e abaixo
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest -v tests/
        
    - name: Build Docker image
      run: |
        docker build -t todo-app .
        
  deploy:    # ⬅️ MANTENHA o job deploy como está
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t meu-projeto-devops .
        
    - name: Simulate deployment
      run: |
        echo "Deploy realizado com sucesso para a branch main!"